config/routes.rb
Rails.application.routes.draw do

  # get "users/add_interest", to: "users#add_interest"
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    get "users/add_interest", to: "users/registrations#add_interest"
    patch "users/update_interest", to: "users/registrations#update_interest"
  end
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact_us", to: "pages#contact_us"
  get "/bookings/confirmed", to: "bookings#confirmed", as: "booking_confirmed"
  get "/bookings/completed", to: "bookings#completed", as: "booking_completed"

  resources :activities do
    resources :bookings, only: [:show, :new, :create, :edit, :update]
    resources :bookings, only: [:destroy], as: :booking_destroy
    member do
      post 'favorite', to: "activities#toggle_favorite"
    end
  end

  resources :bookings, only: :index do
    resources :participant_reviews, only:  [:show, :new, :create, :edit, :update]
  end

  resources :participant_reviews, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :favorites, only: [:index]
  # resources :users, only: :index do
  #   member do
  #     post 'favorite', to: "users#toggle_favorite"
  #   end
  # end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  monetize :price_cents
  validates :name, presence: true
  validates :description, presence: true
  validates :photos, presence: true
  validates :price_cents, numericality: { greater_than_or_equal_to: 0 }
  validates :max_capacity, presence: true
  validates :meeting_location, presence: true
  validates :name, uniqueness: true
  has_many :availabilities, dependent: :destroy
  has_many :bookings, through: :availabilities, dependent: :destroy
  attribute :availabilities_start_time
  acts_as_favoritable
  has_many :faqs
  has_many :bookings, dependent: :destroy
  has_many :participant_reviews, through: :bookings
  has_many :activity_interests
  has_many :interests, through: :activity_interests
  geocoded_by :meeting_location
  after_validation :geocode, if: :will_save_change_to_meeting_location?

  include PgSearch::Model

  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `mahj` will return something!
    }

  def average_rating
    participant_reviews.average(:activity_rating) || 5
  end
end

app/models/activity_interest.rb
class ActivityInterest < ApplicationRecord
  belongs_to :activity
  belongs_to :interest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :activity
  has_many :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  # has_one :host_review
  # has_one :participant_review
  belongs_to :availability
  has_many :participant_reviews, dependent: :destroy
  has_one :chatroom
end

app/models/booking_payment.rb
class BookingPayment < ApplicationRecord
  belongs_to :category
  monetize :price_cents
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  belongs_to :booking

end

## For chatroom flow
# 1.Install:  yarn add @rails/actioncable
# 2.Install database to store memory [Redis]
## On macOS 
# brew update
# brew install redis
# brew services start redis
## On Ubuntu
# sudo apt-get install redis-server 
## 3.If you want to flush your redis store, run [If needed]
# redis-cli flushall

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :activity
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/hdb_town.rb
class HdbTown < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/host_review.rb
class HostReview < ApplicationRecord
  belongs_to :booking
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests
  has_many :activity_interests
  has_many :activities, through: :activity_interests
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  belongs_to :booking
  monetize :amount_cents
end

app/models/participant_review.rb
class ParticipantReview < ApplicationRecord
  belongs_to :booking
  belongs_to :activity
  has_many_attached :photos

  validates :content, presence: true
  validates :user_name, presence: true
  validates :activity_rating, presence: true, numericality: {
    only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  validates :email, format: { with: /\A.*@.*\.com\z/ }
  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :bookings # bookings as a client
  has_many :activities
  has_many :bookings_as_host, through: :activities, source: :bookings
  has_many :orders
  acts_as_favoritor
  geocoded_by :home_address
  after_validation :geocode, if: :will_save_change_to_home_address?
  has_one_attached :avatar
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if user_signed_in? && current_user.home_address != nil
      user_latitude = current_user.latitude
      user_longitude = current_user.longitude
      radius_in_km = 5
      @activities_near_you = Activity.near([user_latitude, user_longitude], radius_in_km).limit(3)
    else
      @activities_near_you = Activity.all.sample(3)
    end
    @activities = Activity.all
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "popup", locals: {activity: activity}),
      }
    end

    if user_signed_in? && current_user.interests.present?
      user_interests = current_user.interests
      @interests_based_activities = Activity.joins(:interests)
                                         .where('activity_interests.interest_id IN (?)', user_interests.map(&:id))
                                         .order('RANDOM()')
                                         .limit(3)
    else
      #without signing in or interests selected, it will show the top activities in the page
      top_rated_activities = Activity.left_joins(:participant_reviews) #user left_joins such that activity without reviews are included too
                                     .group(:id)
                                     .order('AVG(participant_reviews.activity_rating) DESC')
                                     .limit(10)
      @interests_based_activities = top_rated_activities.sample(3)
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToGather</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/reviews/host_review/_form.html.erb
<%= form_for [@booking, @host_review] do |f| %>
  <% if @host_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host_review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @host_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_rating %>
    <%= f.select :user_rating, options_for_select([1, 2, 3, 4, 5]) %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Review" %>
  </div>
<% end %>

app/views/reviews/host_review/_review.html.erb
<p>User rating: <%= host_review.user_rating %></p>

<p>Submitted on <%= host_review.created_at.to_formatted_s(:long) %></p>


<p><%= review.content %></p>
<p>Rating: <%= review.activity_rating %></p>
<p>Rating: <%= review.user_rating %></p>

app/views/reviews/host_review/edit.html.erb
<h1>Edit Host Review</h1>

<%= form_for [@booking, @host_review] do |f| %>
  <% if @host_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host_review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @host_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_rating %>
    <%= f.select :user_rating, options_for_select([1, 2, 3, 4, 5], @host_review.user_rating) %>
  </div>

  <div class="actions">
    <%= f.submit "Update Review" %>
  </div>
<% end %>

app/views/reviews/host_review/new.html.erb
<h1>New Host Review</h1>

<%= form_for [@booking, @host_review] do |f| %>
  <% if @host_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host_review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @host_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_rating %>
    <%= f.select :user_rating, options_for_select([1, 2, 3, 4, 5]) %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Review" %>
  </div>
<% end %>

app/views/reviews/host_review/show.html.erb
<h1>Host Review</h1>

<p>User rating: <%= @host_review.user_rating %></p>

<p>Submitted on <%= @host_review.created_at.to_formatted_s(:long) %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert2 alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer">
  <div class="footer-links">

  </div> %>
  <%# <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div> %>

<div class="footer pt-5 mt-32 tw-bg-black " id="js-footer">
  <div class="container">
    <div class="row row-original">
      <div class="col-12 col-lg-4 mb-32 mb-md-0 footer-p1">
        <div>
          <h4 class="footer-logo">ToGather</h4>
          <p class="tw-text-sm">Welcome to <strong>ToGather</strong>, a community-driven website that connects neighbors through shared activities and moments. Our platform is designed to help you create meaningful connections with the people who live near you, fostering a sense of community and belonging.</p>
        </div>
      </div>
      <div class="col-6 col-lg-2 mb-32 mb-md-0 offset-lg-1 footer-p2">
        <h4 class="tw-text-base text-uppercase font-weight-bold mb-1 title-head">Company</h4>
        <div class="py-1">
          <%= link_to "About Us", contact_us_path, class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Legal Information", "#", class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Contact Us", "#", class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Share Moments", "#", class: "footer-link" %>
        </div>
      </div>
      <div class="col-6 col-lg-2 mb-32 mb-md-0 footer-p2">
        <h4 class="tw-text-base text-uppercase font-weight-bold mb-1">Help Center</h4>
        <div class="py-1">
          <%= link_to "Find Activity", activities_path, class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "How To Host?", "#", class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Host An Activity", new_activity_path(@activity), class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "FAQs", "#", class: "footer-link" %>
        </div>
      </div>
      <div class="col-12 col-lg-3 footer-p2">
        <h4 class="tw-text-base text-uppercase font-weight-bold mb-1">Contact Info</h4>
        <div class="py-1">
          <%= link_to "Phone: 63552828", "#", class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Email: Togather@email.com", "#", class: "footer-link" %>
        </div>
        <div class="py-1">
          <%= link_to "Location: 20 Collyer Quay #23-01 Singpore 049319 ", "#", class: "footer-link" %>
        </div>
          <a href="#" style="margin-right: 7px;"><i class="fab fa-github text-white"></i></a>
          <a href="#" style="margin-right: 7px;"><i class="fab fa-instagram text-white"></i></a>
          <a href="#" style="margin-right: 7px;"><i class="fab fa-facebook text-white"></i></a>
          <a href="#" style="margin-right: 7px;"><i class="fab fa-twitter text-white"></i></a>
          <a href="#" style="margin-right: 7px;"><i class="fab fa-linkedin text-white"></i></a>
      </div>
    </div>
  </div>

  <div class="text-center pt-3 pb-4 tw-bg-black" id="js-copyright">

    <span class="tw-text-xs">© 2023 ToGather | All rights reserved</span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-togather fixed-top">
  <div class="container-fluid">
    <div class="navbar logo-search">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= "ToGather" %>
      <% end %>
      <%= form_with url: activities_path, method: :get, class: "d-flex" do |f| %>
        <div class="input-group input-group-search tw-hidden md:tw-flex">
          <%= f.text_field :query, value: params[:query], placeholder: "Type a keyword", class: "form-control tw-text-xs md:tw-text-sm input-search tw-rounded-tl tw-rounded-bl", aria_label: "Where are you going?", autocomplete: "off" %>
          <%= f.collection_select :location, HdbTown.order(:name), :id, :name, { include_blank: "HDB Towns" }, { id: "js-select-num-guest-header", class: "form-control tw-text-xs md:tw-text-sm input-guest", readonly: true } %>
          <%= f.collection_select :category, Interest.all, :id, :name, {include_blank: "Categories"}, {id: "js-input-start-date-nav", class: "form-control tw-text-xs md:tw-text-sm input-date", readonly: true} %>
          <%= button_tag type: 'submit', class: 'btn btn-primary tw-px-1.5 tw-rounded-tr tw-rounded-br' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" class="tw-text-white">
              <circle cx="11" cy="11" r="8"></circle>
              <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            </svg>
          <% end %>
        </div>
      <% end %>
    </div>

    <%# do %>
      <%# <%= image_tag "ToGather.png" %>
    <%# <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "About Us", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Find Activity", activities_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Moments", participant_reviews_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Host An Activity", new_activity_path(@activity), class: "btn btn-secondary host-activity" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= image_tag url_for(current_user.avatar), class: "avatar-large", alt: "avatar-large", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://www.citypng.com/public/uploads/preview/download-profile-user-round-orange-icon-symbol-png-11639594360ksf6tlhukf.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="nav-link text-center user-name" href="#" data-bs-toggle="dropdown">Welcome <%= current_user.first_name%>!</a>
              <%=link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%=link_to "Favourites", favorites_path, class: "dropdown-item" %>
              <%= link_to "Reservations", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>