config/routes.rb
Rails.application.routes.draw do

  # get "users/add_interest", to: "users#add_interest"
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    get "users/add_interest", to: "users/registrations#add_interest"
    patch "users/update_interest", to: "users/registrations#update_interest"
  end
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact_us", to: "pages#contact_us"
  get "/bookings/confirmed", to: "bookings#confirmed", as: "booking_confirmed"
  get "/bookings/completed", to: "bookings#completed", as: "booking_completed"

  resources :activities do
    resources :bookings, only: [:show, :new, :create, :edit, :update]
    resources :bookings, only: [:destroy], as: :booking_destroy
    member do
      post 'favorite', to: "activities#toggle_favorite"
    end
  end

  resources :bookings, only: :index do
    resources :participant_reviews, only:  [:show, :new, :create, :edit, :update]
  end

  resources :participant_reviews, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :favorites, only: [:index]
  # resources :users, only: :index do
  #   member do
  #     post 'favorite', to: "users#toggle_favorite"
  #   end
  # end
end

app/controllers/participant_reviews_controller.rb
class ParticipantReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create show edit update destroy]
  before_action :set_participant_review, only: [:show, :edit, :update]

  def index
    #code to display all reviews for an activity or a booking
    @participant_reviews = policy_scope(ParticipantReview.joins(:booking).where(bookings: { user_id: current_user }))
  end

  def show
    # This will display the details of the participant review with the given ID
  end

  def new
    @activity = Activity.find(@booking.activity_id)
    @participant_review = ParticipantReview.new(booking: @booking)
    authorize(@participant_review)
  end

  def create
    @activity = Activity.find(@booking.activity_id)
    if @booking.user != current_user
      redirect_to activity_booking_path(@activity, @booking), alert: "You are not authorized to leave a review for this booking"
    elsif @booking.participant_reviews.present?
      redirect_to booking_participant_review_path(@booking, @booking.participant_reviews.first), alert: "You have already reviewed for this booking"
      return
    end
    @participant_review = @booking.participant_reviews.build(participant_review_params)
    @participant_review.user_name = @booking.user_name
    @participant_review.activity = @activity

    authorize(@participant_review)

    if @participant_review.save
      redirect_to activity_booking_path(@activity, @booking), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
    # This will display the edit form for the participant review with the given ID
  end

  def update
    if @participant_review.update(participant_review_params)
      redirect_to booking_participant_review_path(@booking, @participant_review), notice: 'Participant review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @participant_review.destroy
    redirect_to @booking, notice: 'Participant review was successfully deleted.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
    authorize(@booking)
  end

  def set_participant_review
    @participant_review = ParticipantReview.find(params[:id])
    authorize(@participant_review)
  end

  def participant_review_params
    params.require(:participant_review).permit(:content, :activity_rating, photos: [])
  end
end

app/controllers/participantreview_controller.rb
class ParticipantReviewsController < ApplicationController
  before_action :set_booking
  before_action :set_participant_review, only: [:show, :edit, :update, :destroy]

  def new
    @participant_review = ParticipantReview.new
  end

  def create
    @participant_review = ParticipantReview.new(participant_review_params)
    @participant_review.booking = @booking

    if @participant_review.save
      redirect_to @booking, notice: 'Participant review was successfully created.'
    else
      render :new
    end
  end

  def show
    # This will display the details of the participant review with the given ID
  end

  def edit
    # This will display the edit form for the participant review with the given ID
  end

  def update
    if @participant_review.update(participant_review_params)
      redirect_to booking_participant_review_path(@booking, @participant_review), notice: 'Participant review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @participant_review.destroy
    redirect_to @booking, notice: 'Participant review was successfully deleted.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def set_participant_review
    @participant_review = @booking.participant_reviews.find(params[:id])
  end

  def participant_review_params
    params.require(:participant_review).permit(:content, :activity_rating)
  end
end

app/views/participant_reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@booking, @participant_review]) do |f| %>
  <% if @participant_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant_review.errors.count, "error") %> prohibited this participant_review from being saved:</h2>
      <ul>
        <% @participant_review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :activity_rating %>
    <%= f.number_field :activity_rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <%= f.submit "Update Review", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Cancel', booking_participant_review_path(@booking, @participant_review) %>

app/views/participant_reviews/index.html.erb
<div class = "container">
<br>
<br>
<br>
<% counter = 1 %>
<% @participant_reviews.each do |review| %>
  <div>
    <h3>My Moment <%= counter %></h3>
      <div class="gallery-wrap">
        <%= image_tag 'back.png', id: 'backBtn' %>
        <div class="gallery">
          <div>
              <span><% review.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %></span>
              <% end %>
          </div>
        </div>
        <%= image_tag 'next.png', id: 'nextBtn' %>
      </div>
    <p><strong>Happened on</strong> <%= review.booking.availability.start_time.strftime("%A, %B %e, %Y") %></p>
    <p><strong>Rating:</strong> <%= review.activity_rating %></p>
    <p><strong>Description:</strong> <%= review.content %></p>
    <p><strong>User:</strong> <%= review.user_name %></p>
  </div>
  <% counter += 1 %>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>
</div>

app/views/participant_reviews/new.html.erb
<div class="container" style="height: 900px;"><br>
    <div class="container rate-form" style="background: var(--bs-white)">
      <h1>Share Your Moment With Us</h1>
      <%= simple_form_for([@booking, @participant_review]) do |f| %>
        <% if @participant_review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@participant_review.errors.count, "error") %> prohibited this participant_review from being saved:</h2>
            <ul>
            <% @participant_review.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :activity_rating %>
          <div class="rating">
            <% (1..5).each do |i| %>
              <%= f.radio_button :activity_rating, i, id: "activity_rating_#{i}" %>
              <%= label_tag "activity_rating_#{i}", "★" * i, class: "label-star btn btn-outline" %>
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :comment %>
          <%= f.text_area :content, class: "form-control", rows: 3 %>
        </div>

        <div class="form-group">
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: "form-control-file" } %>
        </div>

        <%= f.submit "Submit Review", class: "btn btn-primary" %><br><br>
      <% end %>
        <%= link_to 'Cancel', activity_booking_path(@activity, @booking), class: 'btn btn-primary' %><br><br>
    </div>
</div>

app/views/participant_reviews/show.html.erb
<div class="container">
  <h1>Review</h1>
  <div class="gallery-wrap">
    <%= image_tag 'back.png', id: 'backBtn' %>
    <div class="gallery">
      <div>
          <span><% @participant_review.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %></span>
          <% end %>
      </div>
    </div>
    <%= image_tag 'next.png', id: 'nextBtn' %>
  </div>

  <p><strong>Rating:</strong> <%= @participant_review.activity_rating %></p>
  <p><strong>Description:</strong> <%= @participant_review.content %></p>
  <p><strong>User:</strong> <%= @participant_review.user_name %></p>

  <%= link_to 'Edit', edit_booking_participant_review_path(@booking, @participant_review) if policy(@participant_review).update? %>
  <%= link_to 'Back', activity_booking_path(@participant_review.activity, @booking) %>
</div>