config/routes.rb
Rails.application.routes.draw do

  # get "users/add_interest", to: "users#add_interest"
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    get "users/add_interest", to: "users/registrations#add_interest"
    patch "users/update_interest", to: "users/registrations#update_interest"
  end
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact_us", to: "pages#contact_us"
  get "/bookings/confirmed", to: "bookings#confirmed", as: "booking_confirmed"
  get "/bookings/completed", to: "bookings#completed", as: "booking_completed"

  resources :activities do
    resources :bookings, only: [:show, :new, :create, :edit, :update]
    resources :bookings, only: [:destroy], as: :booking_destroy
    member do
      post 'favorite', to: "activities#toggle_favorite"
    end
  end

  resources :bookings, only: :index do
    resources :participant_reviews, only:  [:show, :new, :create, :edit, :update]
  end

  resources :participant_reviews, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :favorites, only: [:index]
  # resources :users, only: :index do
  #   member do
  #     post 'favorite', to: "users#toggle_favorite"
  #   end
  # end
end

app/models/booking_payment.rb
class BookingPayment < ApplicationRecord
  belongs_to :category
  monetize :price_cents
end

app/controllers/booking_payment_controller.rb
class BookingPaymentController < ApplicationController
    skip_before_action :authenticate_user!

    def index
    @booking_payments = BookingPayment.all
    end

    def show
    @booking_payment = BookingPayment.find(params[:id])
    end

end

app/views/booking_payment/index.html.erb
<div class="container">
  <h1>booking_payments</h1>
  <div class="row">
    <% @booking_payments.each do |booking_payment| %>
      <div class="col-6 col-md-4">
        <div class="card">
          <%= image_tag booking_payment.photo_url , class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= booking_payment.name %></h5>
            <p class="card-text"><%= booking_payment.category.name %></p>
            <p>Amount: <%= humanized_money_with_symbol(booking_payment.price) %></p>
            <%= link_to "More details", booking_payment_path(booking_payment), class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/booking_payment/show.html.erb
<div class="container py-3">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= image_tag(@booking_payment.photo_url, width: '100%') %>
    </div>
    <div class="col-sm-12 col-md-6">
      <h1><%= @booking_payment.name %></h1>
      <p>Some awesome description of our amazing teddy.</p>
      <p>$$$</p>
      <p>Amount: <%= humanized_money_with_symbol(@booking_payment.price) %></p>
    </div>
  </div>
</div>