config/routes.rb
Rails.application.routes.draw do

  # get "users/add_interest", to: "users#add_interest"
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_scope :user do
    get "users/add_interest", to: "users/registrations#add_interest"
    patch "users/update_interest", to: "users/registrations#update_interest"
  end
  root to: "pages#home"
  get "/about", to: "pages#about"
  get "/contact_us", to: "pages#contact_us"
  get "/bookings/confirmed", to: "bookings#confirmed", as: "booking_confirmed"
  get "/bookings/completed", to: "bookings#completed", as: "booking_completed"

  resources :activities do
    resources :bookings, only: [:show, :new, :create, :edit, :update]
    resources :bookings, only: [:destroy], as: :booking_destroy
    member do
      post 'favorite', to: "activities#toggle_favorite"
    end
  end

  resources :bookings, only: :index do
    resources :participant_reviews, only:  [:show, :new, :create, :edit, :update]
  end

  resources :participant_reviews, only: :index

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :favorites, only: [:index]
  # resources :users, only: :index do
  #   member do
  #     post 'favorite', to: "users#toggle_favorite"
  #   end
  # end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  monetize :price_cents
  validates :name, presence: true
  validates :description, presence: true
  validates :photos, presence: true
  validates :price_cents, numericality: { greater_than_or_equal_to: 0 }
  validates :max_capacity, presence: true
  validates :meeting_location, presence: true
  validates :name, uniqueness: true
  has_many :availabilities, dependent: :destroy
  has_many :bookings, through: :availabilities, dependent: :destroy
  attribute :availabilities_start_time
  acts_as_favoritable
  has_many :faqs
  has_many :bookings, dependent: :destroy
  has_many :participant_reviews, through: :bookings
  has_many :activity_interests
  has_many :interests, through: :activity_interests
  geocoded_by :meeting_location
  after_validation :geocode, if: :will_save_change_to_meeting_location?

  include PgSearch::Model

  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `mahj` will return something!
    }

  def average_rating
    participant_reviews.average(:activity_rating) || 5
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show edit update destroy toggle_favorite]

  def index
    if params[:query].present?
      @activities = policy_scope(Activity.search_by_name_and_description(params[:query]))
    else
      @activities = policy_scope(Activity).order("RANDOM()")
    end
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "popup", locals: {activity: activity}),
      }
    end
  end

  def show
    @bookings = @activity.bookings
    @participant_reviews = ParticipantReview.where(booking_id: @bookings.pluck(:id))
    @booking = Booking.new
    @marker = [{
      lat: @activity.latitude,
      lng: @activity.longitude
    }]
  end

  def new
    @activity = Activity.new
    authorize(@activity)
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    availabilities = availability_params[:availabilities_start_time].split(", ")
    availabilities.map { |time| @activity.availabilities.build(
      start_time: time,
      end_time: time
      )
    }
    interests = params["activity"]["interest_ids"]
    interests.each do |interest|
      @activity.interests << Interest.find(interest.to_i)
    end
    authorize(@activity)
    if @activity.save!
      redirect_to activity_path(@activity), notice: "Activity was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to activity_path(@activity), notice: "Activity was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity.destroy
    redirect_to activities_path, notice: "Activity was successfully destroyed."
  end

  def toggle_favorite
    current_user.favorited?(@activity) ? current_user.unfavorite(@activity) : current_user.favorite(@activity)
  end

  # def add_interest

  #   interests = params["user"]["interest_ids"] # array of selected interest ids
  #   interests.each do |interest_id|
  #     unless current_user.interests.exists?(id: interest_id.to_i)
  #       UserInterest.create(user: current_user, interest_id: interest_id.to_i)
  #     end
  #   end
  #   respond_to do |format|
  #     format.html { redirect_to root_path, notice: "Interests have been updated" }
  #     format.text { render partial: "update_interest", formats: [:html]}
  #   end
  # end

  private

  def set_activity
    @activity = Activity.find(params[:id])
    authorize(@activity)
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :price, :max_capacity, :meeting_location, :minimum_age, :policies, interests: [], photos: [])
  end

  def availability_params
    params.require(:activity).permit(:availabilities_start_time)
  end
end

app/views/activities/_activity.html.erb
<div id="myModal" class="modal">
  <div class="modal-content">
    <div class="modal-header">
    <h2 id="activity-name"></h2>
    <span class="close">&times;</span>
  </div>
    <p id="activity-description"></p>
    <p id="activity-meeting-location"></p>
    <p id="activity-policies"></p>
    <p id="activity-availabilities"></p>
  <div class="container" style="text-align: center;">
    <%= link_to "View Activity", "#", id: "view-activity-link", class: "btn btn-primary w-30" %></div>
  </div>
</div>

<script>
// Get the modal
var modal = document.getElementById("myModal");
var viewActivityLink = document.getElementById("view-activity-link");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// Get the activity name, description, meeting location, policies, and title elements in the modal
var activityName = document.getElementById("activity-name");
var activityDescription = document.getElementById("activity-description");
var activityMeetingLocation = document.getElementById("activity-meeting-location");
var activityPolicies = document.getElementById("activity-policies");
var activityAvailabilities = document.getElementById("activity-availabilities");
var modalTitle = document.getElementById("modal-title");

// When the user clicks the button, open the modal and set the title, activity name, description, meeting location, and policies
function showPopup(name, description, meetingLocation, policies, availabilities, activityPath) {
  modal.style.display = "block";
  activityName.innerHTML = name;
  activityDescription.innerHTML = "<span style='text-decoration: underline;'><strong>About Activity</span></strong><ul><li>" + description;
  activityMeetingLocation.innerHTML = "<span style='text-decoration: underline;'><strong>Meeting Location</span></strong><ul><li>" + meetingLocation;
  activityPolicies.innerHTML = "<span style='text-decoration: underline;'><strong>Things to Note</span></strong><ul><li>" + policies;
  activityAvailabilities.innerHTML = "<span style='text-decoration: underline;'><strong>Upcoming Available Date</span></strong><ul><li>" + availabilities;
  viewActivityLink.href = activityPath;
}


// When the user clicks on <span> (x), close the modal
span.onclick = function () {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function (event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}

</script>

<% availabilities = activity.availabilities.map {|availability| availability.start_time.strftime("%A, %B %e, %Y") }.take(7).join(", ") %>


<div id="<%= dom_id activity %>" class="activity-card col-sm-3">

<div class="activity-image-container">
  <div class="activity-card-image" style="background-image: url(<%= cl_image_path activity.photos.sample.key %>)">
    <span class="fa-stack fa-lg" onclick='showPopup("<%= activity.name %>", "<%= activity.description %>", "<%= activity.meeting_location %>", "<%= activity.policies %>",
      "<%= availabilities %>","<%= activity_path(activity) %>")'>
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-calendar fa-stack-1x fa-inverse"></i>
    </span>
  </div>
</div>

<div class="activity-details">
  <div style="display: flex; justify-content: space-between;">
  <a href="<%= activity_path(activity) %>" style="text-decoration: none;">
      <h2 class="activity-name"><%= activity.name %></h2>
    </a>


  <% if user_signed_in? %>
        <div data-controller="favorite" style="margin-left: 50px;">
          <%= link_to favorite_activity_path(activity), data: {turbo_method: :post, action: "click->favorite#update"} do %>
            <i class="fa-heart <%= current_user.favorited?(activity) ? "fa-solid" : "fa-regular" %>" data-favorite-target="bookmark"></i>
          <% end %>
        </div>
      <% end %>

  </div>

    <p class="activity-info" style="display: inline-block">
    <strong><%= activity.average_rating %></strong>
    <span class="fa fa-star yellow-star"></span>
    <span class="circle circle--4 circle--gray ml-1 mr-1 align-middle"></span>
    Hosted by
    <strong><%= activity.user.first_name %></strong>
    <span class="circle circle--4 circle--gray ml-1 mr-1 align-middle"></span>
    At <strong><%= activity.meeting_location.sub(/,\s*Singapore$/, '') %></strong>
    </p>

    <%# <p class="activity-description" style="color: grey"><%= activity.description %>

    <div>
      <p class="activity-price" style="font-size: 18px; color: grey; justify-content: space-between;display: flex;">
        <strong>From <%= humanized_money_with_symbol(activity.price) %></strong>
        <%= link_to "View Activity", activity_path(activity), class: "btn btn-primary", style: "margin-left: 95px;" %>
      </p>
    </div>

  </div>

</div>

app/views/activities/_form.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <%= simple_form_for(activity, data: { controller: "activity-flatpickr" }, html: {class: "form-horizontal"}) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-group">
              <%= f.input :name, class: "form-control", placeholder: "Enter activity name" %>
            </div>

            <div class="form-group">
              <%= f.input :description, as: :text, input_html: { class: "form-control", rows: 4, placeholder: "Enter activity description" } %>
            </div>

            <div class="form-group">
              <%= f.input :price, class: "form-control", placeholder: "Enter price" %>
            </div>

            <div class="form-group">
              <%= f.input :max_capacity, class: "form-control", placeholder: "Enter maximum capacity" %>
            </div>

            <div class="form-group">
              <%= f.input :availabilities_start_time, as: :string, input_html: { class: "form-control", data: { activity_flatpickr_target: "availabilities" }, placeholder: "You may select multiple dates" }, label: "Availabilities" %>
            </div>

            <div class="form-group">
              <%= f.input :meeting_location, class: "form-control", input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class: "position-relative"} %>
            </div>

            <div class="form-group">
              <%= f.input :minimum_age, class: "form-control", placeholder: "Enter minimum age" %>
            </div>

            <div class="form-group">
              <%= f.input :policies, as: :text, class: "form-control", input_html: { placeholder: "Eg. No pets allowed", rows: 2 }, label: "Things to Note" %>
            </div>

            <div class="form-group">
              <%= f.association :interests, as: :check_boxes, label: "Select categories", collection: Interest.all, include_hidden:false, input_html: { class: "form-check-input" } %>
            </div>

            <div class="form-group">
              <%= f.input :photos, as: :file, input_html: { multiple: true, class: "form-control-file" } %>
            </div>

            <div class="form-group text-center">
              <div>
                <%= f.button :submit, class: "btn btn-primary btn-form" %>
              </div>
              <div class="btn-back text-center mt-5">
                <%= link_to "Back", activities_path, class: "btn btn-secondary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <br>
      <br>
    </div>
  </body>
</html>

app/views/activities/_modelpopup.html.erb
<h1 class="popup-small-heading"><%= activity.name %></h1>
<p><%= activity.meeting_location %></p>

app/views/activities/_popup.html.erb
<h1 class="popup-small-heading"><%= activity.name %></h1>
<p><%= activity.meeting_location %></p>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<div class="container"><br>
  <div data-controller="map"
      id='map'
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-markers-value="<%= @markers.to_json %>"
      style='width: 100%; height: 300px;'></div>
  </div>

  <div class="row justify-content-center">
    <div class="col-sm-9">
      <div class="activities">
        <% if @activities.any? %>
          <% @activities.each do |activity| %>
          <br>
              <%= render activity %>
          <% end %>
        <% else %>
          <em>Sorry, no activities found.</em>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Host an Activity with Togather</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background-image"></div>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-8">
          <div class="host-container-box new-booking">
            <h1 class="text-center mb-5">Host an Activity with us!</h1>
            <div class="horizontal-line"></div>
            <h5 class="heading-text">ToGather has something for everyone. We believe that everyone has something to offer, and we encourage all members of our community to get involved and share their talents and passions. Through ToGather, you can discover new hobbies, meet new people, and build relationships that will last a lifetime.</h5>
            <div class="horizontal-line"></div>
            <br>
            <%= render "form", activity: @activity %>
            <!-- Add a container div for the buttons and center them using Bootstrap classes -->
            <%# <div class="btn-container text-center mt-5"> %>
              <%# <%= link_to "Back", activities_path, class: "btn btn-secondary" %>
            <%# </div> %>
          </div>
        </div>
      </div>
    </div>

    <br>
    <br>
    <br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/activities/show.html.erb
<div class="activity-details">
  <div class="container"><br><br>
    <div class="row activity-details-each">
      <h2 class="activity-title" style="font-weight: bold;"><%= @activity.name %></h2>
      <div class="horizontal-line"></div>
      <div>
        <p class="activity-host" style="display: inline-block;margin-bottom: 1px;">
          <strong>Hosted by <%= @activity.user.first_name %><strong>
        <span class="circle circle--4 circle--grey ml-1 mr-1 align-middle"></span>
        <%= @activity.average_rating %>
        <span class="fa fa-star yellow-star"></span>
        <span class="circle circle--4 circle--grey ml-1 mr-1 align-middle"></span>
        <strong>Posted on <%= @activity.posteddate %></strong>
      </div>

      <div class="gallery-wrap">
        <%= image_tag 'back.png', id: 'backBtn' %>
        <div class="gallery">
          <div>
              <span><% @activity.photos.each do |photo| %>
              <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %></span>
              <% end %>
          </div>
        </div>
        <%= image_tag 'next.png', id: 'nextBtn' %>
    </div>

    <div class="row">
      <div class="col">
        <h1 class="activity-title" style="font-weight: bold">Details</h1>
        <div class="normal-line"></div>
        <ul class="diamond-bullet">
          <p>Description</p>
          <li style="margin-top: 1rem; color:grey"><%= @activity.description %></li><br>
          <p>Things to take note</p>
          <li style="margin-top: 1rem; color:grey"><%= @activity.policies %></li><br>
          <p>Price</p>
          <li style="margin-top: 1rem; color:grey"><%= humanized_money_with_symbol(@activity.price) %> per pax</li>
        </ul>
      </div>
      <div class="col booking-form text-center">
        <div class="booking-activity-form">
          <h5 class="activity-name-booking" style="font-weight: bold">Booking</h5>
          <div class="normal-line"></div>
          <%= render "/bookings/form", activity: @activity, booking: @booking %>
        </div>
      </div>
      
    </div><br>

    <div class="container">
      <div class="row meeting">
        <h1 class="activity-title" style="font-weight: bold">Where to meet?</h1>
        <div class="normal-line"></div>
        <p style="color:grey">Let's meet at <u><strong><%= @activity.meeting_location %></strong></u></p>
          <div data-controller="map"
            id='map'
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
            data-map-markers-value="<%= @marker.to_json %>"
            style='width: 100%; height: 400px;'>
          </div>
      </div>
    </div><br>
    <div class="container">
      <div class="row faqs">
        <div class="faqs-each">
          <h1 class="activity-title" style="font-weight: bold">Common FAQs from the Community</h1>
          <div class="normal-line" style="font-weight: bold"></div>
            <% @activity.faqs.each do |faq| %>
            <ul class="diamond-bullet">
              <li>
                <%= faq.question %>
                <p style="color:grey"><strong>Ans:</strong> <%= faq.answer %></p>
              </li>
            </ul>
            <% end %>
        </div>
      </div>
    </div>
    <br>
    <div class="container">
      <div class="row faqs">
        <h1 class="activity-title" style="font-weight: bold">Reviews</h1>
        <div class="normal-line"></div>
        <% if @participant_reviews.present? %>
          <% @participant_reviews.each do |review| %>
            <div class="review">
              <p><strong>User Name:</strong> <%= review.user_name %></p>
              <p><strong>Rating:</strong> <%= review.activity_rating %></p>
              <p><strong>Content:</strong> <%= review.content %></p>
              <%# <p><%= link_to "Edit", edit_booking_review_path(@booking, review) %></p>
              <%# <p><%= link_to "Delete", booking_review_path(@booking, review), method: :delete, data: { confirm: "Are you sure you want to delete this review?" } %></p>
            </div>
          <% end %>
        <% else %>
          <p>No reviews yet.</p>
        <% end %>
      </div>
      <div>
        <% if policy(@activity).edit? %>
          <%= link_to "Edit this activity", edit_activity_path(@activity), class: "btn btn-primary" %>
        <% end %>
        <%= link_to "Back to activities", activities_path, class: "btn btn-primary" %><br><br>
        <%= button_to "Destroy this activity", @activity,class: "btn btn-primary", method: :delete if policy(@activity).destroy? %>
      </div>
    </div>
  </div>
</div>

<br>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    let scrollContainer = document.querySelector(".gallery");
    let backBtn = document.getElementById("backBtn");
    let nextBtn = document.getElementById("nextBtn");

    scrollContainer.addEventListener("wheel", (evt) => {
      evt.preventDefault();
      scrollContainer.scrollLeft += evt.deltaY;
    });
  });
</script>